package health

import (
	"fmt"
	"github.com/covoyage/covo-agent/internal/cli"
	"path/filepath"

	"github.com/covoyage/covo-agent/internal/crash"
	"github.com/spf13/cobra"
)

func NewCrashReportCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "crash-report [list|show <filename>]",
		Short: "View crash reports from previous crashes",
		Long: "View and manage crash reports generated by the crash handler.\n\n" +
			"  covo-agent crash-report list       — list all crash reports\n" +
			"  covo-agent crash-report show <id>  — show a specific crash report\n" +
			"  covo-agent crash-report            — show the most recent crash report",
		Args: cobra.MaximumNArgs(2),
		RunE: func(_ *cobra.Command, args []string) error {
			homeDir, err := cli.EnsureHomeDir()
			if err != nil {
				return fmt.Errorf("ensure home dir: %w", err)
			}

			sub := ""
			if len(args) > 0 {
				sub = args[0]
			}

			switch sub {
			case "list", "ls":
				return listCrashReports(homeDir)
			case "show", "view":
				if len(args) < 2 {
					return fmt.Errorf("usage: covo-agent crash-report show <filename>")
				}
				return showCrashReport(homeDir, args[1])
			case "":
				// Show most recent
				return showMostRecentCrashReport(homeDir)
			default:
				return fmt.Errorf("unknown subcommand %q (use: list, show)", sub)
			}
		},
	}

	return cmd
}

func listCrashReports(homeDir string) error {
	reports, err := crash.ListReports(homeDir)
	if err != nil {
		return fmt.Errorf("list crash reports: %w", err)
	}

	if len(reports) == 0 {
		fmt.Println("No crash reports found.")
		return nil
	}

	fmt.Printf("── Crash Reports (%d) ──\n", len(reports))
	for _, r := range reports {
		fmt.Printf("  %s  %s  (%s)\n", r.Modified.Format("2006-01-02 15:04:05"), r.Filename, formatSize(r.Size))
	}
	fmt.Println("\nUse 'covo-agent crash-report show <filename>' to view a report.")
	return nil
}

func showCrashReport(homeDir string, filename string) error {
	path := filepath.Join(homeDir, "crash-reports", filename)
	report, err := crash.LoadReport(path)
	if err != nil {
		return fmt.Errorf("load crash report: %w", err)
	}
	fmt.Print(crash.FormatReport(report))
	return nil
}

func showMostRecentCrashReport(homeDir string) error {
	reports, err := crash.ListReports(homeDir)
	if err != nil {
		return fmt.Errorf("list crash reports: %w", err)
	}

	if len(reports) == 0 {
		fmt.Println("No crash reports found.")
		return nil
	}

	mostRecent := reports[0]
	report, err := crash.LoadReport(mostRecent.Path)
	if err != nil {
		return fmt.Errorf("load crash report: %w", err)
	}
	fmt.Print(crash.FormatReport(report))
	return nil
}

func formatSize(bytes int64) string {
	if bytes < 1024 {
		return fmt.Sprintf("%dB", bytes)
	}
	if bytes < 1024*1024 {
		return fmt.Sprintf("%.1fKB", float64(bytes)/1024)
	}
	return fmt.Sprintf("%.1fMB", float64(bytes)/(1024*1024))
}
